--- 
title: "TP CEFIM"
author: "Oswaldo Forey"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
# output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: openscapes/series
description: "Un TP pour la promo 2022 du CEFIM"
editor_options: 
  chunk_output_type: console
---

# Analyse des données mondiales

# POPULATION - Données UN 1950-2020

```{r DONNEES POPULATION MONDIALE}

library(tidyverse)
# faire un csv en premier, passer les '"..." en na et utiliser la virgule comme marque de la décimale
population_1950_UN<-read_delim("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.csv",
                       locale=locale(decimal_mark=","),  
                       skip=16,
                       na="...") |> 
  rename(region=3)  |> 
  select(region,Type,"1950":"2020") |> 
  pivot_longer(cols="1950":"2020",
               names_to = "annee",
               values_to="population") |> 
  mutate(annee=as.integer(annee))

# exploration des pays

pop_pays<-population_1950_UN |> distinct(region)

# codes iso

iso_codes_pays<-read_delim("countries_iso_codes.csv") |> 
  select(name,iso_code="alpha-3",region,sub_region="sub-region",
         intermediate_region="intermediate-region")

# liste des pays avec des codes iso

iso_codes_pays_regions<-iso_codes_pays |>
  distinct(region)

# fusion du tableau avec les valeurs de population avec celui avec les codes iso
pop_codes_iso<-full_join(population_1950_UN,iso_codes_pays,by=c("region"="name"))

# identification des pays sans code iso pour recodage

pop_no_codes_iso<-anti_join(pop_pays,iso_codes_pays,by=c("region"="name")) |> 
  distinct(region)

# recodage des pays manquants; on regarde dans la tableau pop_codes_iso pour voir les différences d'orthographe

population_1950_UN_consolide<-population_1950_UN |> 
  mutate(region=case_when(region=="Republic of Moldova"~"Moldova, Republic of",
                            region=="United Kingdom"~"United Kingdom of Great Britain and Northern Ireland",
                            region=="United Republic of Tanzania
"~"Tanzania, United Republic of",
                            TRUE~region)) 
 
############################ DONNEES FINALES CONSOLIDEES ISO ###################### 

# on refusionne avec les bons pays

population_1950_UN_iso<-full_join(population_1950_UN_consolide,
                                            iso_codes_pays,by=c("region"="name"))

##################################### DONNEES BRUTES QUE LES PAYS ####################
# Refusion avec un join qui ne conserve que les pays du tableaux iso_codes_pays

population_1950_UN_iso_pays<-right_join(population_1950_UN_consolide,
                                            iso_codes_pays,by=c("region"="name"))

pop_pays_uniquement<-population_1950_UN_iso_pays |> distinct(region)

```

## Population graphique monde entier

```{r GRAPHIQUE MONDE ENTIER}

## Graphique 1 : évolution de la population mondiale (pas très informatif)

# exploration légendes zone géographique

population_1950_UN_iso |> distinct(Type)

# graphique pour le monde entier

population_1950_UN_iso |>  
  filter(Type=="World") |> 

# pour faire un geom_line
# https://statisticsglobe.com/ggplot2-geom_path-each-group-only-one-observation-in-r
ggplot()+
  aes(annee,population,group=1)+
  geom_point()+
  geom_line(size=2)+
  theme(axis.text.x=element_text(angle=45,
                                 hjust=1,
                                 vjust=1))

# graphique 2 : évolution de la population par continent

# on regarde les niveaux de la colonne region une fois dans la catégorie Subregion de la colonne Type pour voir comment rassembler le plus simplement possible
population_1950_UN_iso |>   
  filter(Type=="Subregion") |>
  distinct(region)

# on rassemble les régions dans des continents en extrayant le dernier mot à droite dans une nouvelle colonne

continent_population<-population_1950_UN_iso |>  
  filter(Type=="Subregion") |> 
  mutate(continent=word(region,start = -1),
         .after=Type) |> 
  mutate(region=fct_reorder(region,continent)) |> 
  group_by(annee,continent) |> 
  summarise(pop_sum=sum(population,na.rm=TRUE)) |> 
  ungroup()

# vérification que tout va bien
continent_population|> 
  distinct(continent)

# pour faire un geom_line
# https://statisticsglobe.com/ggplot2-geom_path-each-group-only-one-observation-in-r
ggplot(continent_population )+
  aes(annee,pop_sum,colour=continent)+
  #geom_point()+
  geom_line(size=1)+
  #facet_grid(~continent)+
  scale_x_continuous(breaks=seq(0,2020,10))+
  #scale_y_continuous(breaks=seq(0,2020,10))+
  theme(axis.text.x=element_text(angle=45,
                                 hjust=1,
                                 vjust=1))

# verification des valeurs de population

test<-continent_population |> 
  filter(annee==2020)


```


